### ISSUE TITLE
Highlight those code blocks only with a class?

### ISSUE THREAD

**Issue by aalimovs** [Bloggify/showdown-highlight#11]
Hi,

I've got a 2 code blocks:

```
~~~
define foobar() {
    print "Welcome to flavor country!";
}
~~~

~~~python
import time
# Quick, count to ten!
for i in range(10):
    # (but not *too* quick)
    time.sleep(0.5)
    print(i)
~~~
```

However, they are being rendered as:

<img width="534" alt="screen shot 2018-09-22 at 13 13 22" src="https://user-images.githubusercontent.com/6516539/45917161-56afb780-be69-11e8-8ddd-08919de58a27.png">

Notice the unnecessary `hljs` string at the beginning of the first code block, looks like a bug?

Here's the HTML:

<img width="454" alt="screen shot 2018-09-22 at 13 16 10" src="https://user-images.githubusercontent.com/6516539/45917181-be660280-be69-11e8-8cfd-cbe7e35c1016.png">

Should the library just ignore code blocks that don't have a class defined?

**Comment by obedm503** [comment]
I've been having the same issue. From reading the current code, it seems the author decided that if not language is found, then hightlight.js should decide with [`hljs.highlightAuto`](https://github.com/Bloggify/showdown-highlight/blob/2ef05aa7cc18df8725c036535545af8f99091b83/lib/index.js#L20-L24).

this seems sensible enough, but the extension ignores the fact that if no language was defined, showdown doesn't even add a `class` attribute. the code breaks and ends up adding `"hljs "` at the beginning of the block.
