### ISSUE TITLE
Inline code doesn't appear to be highlighted

### ISSUE THREAD

**Issue by bgrubb83** [Bloggify/showdown-highlight#16]
Code blocks with the following format:

```js
console.log('hi');
```

are highlighted correctly, because the hljs classes are added as expected. However inline code such as:

This is a line of text which contains inline code of `console.log('hi');` within it.

doesn't seem to  have the hljs classes added, so no highlighting occurs.

Am I doing something wrong, or does showdown-highlight / highlightjs not support inline code?

Thanks.

**Comment by IonicaBizau** [comment]
This is expected, it's a common thing in the Markdown renderers. The inline code blocks are not highlighted.
