### ISSUE TITLE
Is there anyway to inline css classes?

### ISSUE THREAD

**Issue by kuncevic** [Bloggify/showdown-highlight#36]
First of all thanks for building a great highlight.js integration.

I am wondering is there anyway to make the [styles inline](https://github.com/showdownjs/showdown/issues/860)?

What I want is instead of `<element class="js language-js">` to have this `<element style="....">`

**Comment by IonicaBizau** [comment]
Currently that's not possible, but I am wondering if highlight.js would
support it. If so, we could add an option for it.

**Comment by kuncevic** [comment]
Right, I more looking into solution that not just limited to highlight.js use-case. 
Seems like I need to writhe my own [output extension ](https://github.com/showdownjs/showdown/wiki/Cookbook:-Using-language-and-output-extensions-on-the-same-block#code-fiddle-here-httpjsfiddlenettivie1rqr7xy8) to achieve that.
