### ISSUE TITLE
Upgrade to highlight.js 11

### ISSUE THREAD

**Issue by edi9999** [Bloggify/showdown-highlight#37]
highlight.js 11 came out in May this year https://highlightjs.org/#news-142 

I don't know what exactly changes from a user perspective, but it would be cool to upgrade :)

**Comment by IonicaBizau** [comment]
We could upgrade and if there are breaking changes, we can just release a new major version. Contributions are welcome! :smile:

**Comment by IonicaBizau** [comment]
Fixed in 3.0.0 🎉
