### ISSUE TITLE
Add an option to disable auto language detection

### ISSUE THREAD

**Issue by Phryxia** [Bloggify/showdown-highlight#41]
Before the discussion, I'd like to thank for this great library! The proposal is very simple. Can we add an option **to disable the language auto detection**? 

The usage for this is to express some errors or terminal related things with code fences. For example, if I render a block of code with language unspecified, then it looks like:

![image](https://user-images.githubusercontent.com/7694910/189581829-ae3358af-07e0-4f1f-a3c2-56e2a8e89d7e.png)

~~One can be modified like this. This won't break current behavior. If language is not specified with no auto detection, there is no reason to pass this extension. That's the reason I edited the left regexp.~~ Since I misunderstood something, I deleted previous posted code.

I'd like to listen your feedback before I do that. 

(+ I'm work in progress for this)

**Comment by IonicaBizau** [comment]
This is a great idea, @Phryxia! Would you like to create a PR request for this?

**Comment by Phryxia** [comment]
@IonicaBizau 
Thank you! I'll work for this right away.
